### ISSUE TITLE
Documentation: runtime doesn't mean runtime

### ISSUE THREAD

**Issue by majelbstoat** [formatlos/next-env#7]
It might be worth mentioning in the documentation that even NEXT_PUBLIC_ prefixed keys aren't read from the environment at runtime (i.e., when a browser requests a page). Instead they are fixed at page build time.

So, for instance, when running next build, and then deploying that code to an environment with NEXT_PUBLIC_MY_VAR=hello, NEXT_PUBLIC_MY_VAR will not be set to hello unless it was also set in the environment when next build was run.

(I had thought this was differentiated from Next's new built-in env support in this way.)

**Comment by formatlos** [comment]
@majelbstoat I'd think that it's clear by itself. The environment where you define your variables is the sever, how should a client directly read variables from a file on the server? 

I'm also explaining under "How it works" that it is "using Next.js publicRuntimeConfig internally".

**Comment by majelbstoat** [comment]
There's no reason in principle, for example, that the values of env variables couldn't be taken at runtime (next start), instead of at build time (next build). I understand that's not how it works, which is fine, but runtime implies the time at which it is run (and has nothing to do with being sent to the client - runtime evaluated env variables are just as valid for server only use; should i enable tracing logic? where should i log things? etc). 

The specific use-case here is building a docker image once, then running it in multiple environments that differ only by env variables. You might do that for staging vs production. Or you might do it because you're delivering enterprise software that needs customer-supplied clientids/keys to work etc.

No issues with you not updating it, just identifying an area of confusion.

**Comment by formatlos** [comment]
> There's no reason in principle, for example, that the values of env variables couldn't be taken at runtime (next start), instead of at build time (next build).

I'm not sure what you mean by that, I think you didn't fully understand how this library is working or you have another definition for run/build time.

For clarification:

`NEXT_STATIC_` variables will be evaluated at build time and therefore will be statically included in the js bundle, which means the contents of the variable will be in the js file in plain text.

`NEXT_PUBLIC_` variables will be evaluated at runtime time. Runtime in terms of SSR means, that the variable will be injected in the html-output in the SSR phase (what you call `page build time`).

`NEXT_SERVER_` (or any other ENV variable) will be loaded into memory on the node-server when starting the application, therefore they will be available only in the SSR phase. They are not injected at all. (that is the place for real secret values).

In general there are only 2 ways to hand-over configuration variables from a server to the client:
- injecting it in one of the files loaded from server (html, js, json, ...)
- setting a cookie

> The specific use-case here is building a docker image once, then running it in multiple environments that differ only by env variables. 

The library was built exactly for that use-case and is used in different enterprise applications for years. 

> and has nothing to do with being sent to the client - runtime evaluated env variables are just as valid for server only use

This sounds like you only want different configuration on node-side. For this scenario you don't need this or any other library at all, just use `process.env.`. Just be aware that you can't use the variable in any place that will be used in client-side rendering.

**Comment by majelbstoat** [comment]
I'm just going to try and explain what I mean one more time.

```
$ npx create-next-app
$ cd my-app
$ yarn add next-env
$ echo 'module.exports = require("next-env")({publicPrefix: "CUSTOM_PUBLIC_"})({ poweredByHeader: false });' > next.config.js

// Edit pages/index.js to include <h2>{`COLOR ${process.env.CUSTOM_PUBLIC_COLOR}`}</h2>

$ export CUSTOM_PUBLIC_COLOR=green
$ yarn dev
$ curl localhost:3000 | grep -E -o '.{20}COLOR.{20}'

// Observe that it's green, as expected, in both SSR-rendered HTML, and in NEXT_DATA.

$ CUSTOM_PUBLIC_COLOR=orange yarn build
$ env | grep CUSTOM_PUBLIC

// Observe that our runtime environment is green.

$ yarn start
$ curl localhost:3000 | grep -E -o '.{20}COLOR.{20}'

// Observe that it's orange in the SSR-rendered HTML, and not present in NEXT_DATA.
// Visiting in the browser, notice that the page first renders `COLOR orange` and then renders `COLOR undefined` once client-side rendering kicks in.
```

My expectations running this set of steps would be that the final output in the browser would have `COLOR green` and stay as `COLOR green`.

**Comment by formatlos** [comment]
You are technically not using SSR but SSG, which can't have runtime variables for obvious reasons. Since v9 next.js does so called [Automatic Static Optimization](https://nextjs.org/docs/advanced-features/automatic-static-optimization) it automatically determines that a page is static and prerenders it. 

To opt-out of pre-rendering you need to make your page "dynamic" by adding a `getInitialProps` method to your page. Try `Home.getInitialProps = () => ({});` and the lib should work as expected.

**Comment by formatlos** [comment]
And that could indeed need a short hint the readme.

**Comment by majelbstoat** [comment]
Ah, thank you for the clarification. I've confirmed that that works, and I appreciate it :)
